"""empty message

Revision ID: 15b340f346ea
Revises: 3ea38cb13b40
Create Date: 2014-04-10 11:28:51.488266

"""

# revision identifiers, used by Alembic.
revision = '15b340f346ea'
down_revision = '3ea38cb13b40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unverified__user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('conf_key', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conf_key'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column(u'user', sa.Column('confirmation_key', sa.String(length=20), nullable=True))
    op.add_column(u'user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column(u'user', 'password_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column(u'user', 'password')
    op.drop_column(u'user', 'confirmed')
    op.drop_column(u'user', 'confirmation_key')
    op.drop_table('unverified__user')
    ### end Alembic commands ###
