"""empty message

Revision ID: 16786d0e2458
Revises: 15b340f346ea
Create Date: 2014-04-10 12:22:35.708460

"""

# revision identifiers, used by Alembic.
revision = '16786d0e2458'
down_revision = '15b340f346ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
