"""empty message

Revision ID: 2dbb2857331
Revises: 14eebce173c1
Create Date: 2014-04-10 13:38:54.625555

"""

# revision identifiers, used by Alembic.
revision = '2dbb2857331'
down_revision = '14eebce173c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
