"""empty message

Revision ID: 4d5fc878a899
Revises: 2c04ccc25365
Create Date: 2014-03-25 23:12:22.990424

"""

# revision identifiers, used by Alembic.
revision = '4d5fc878a899'
down_revision = '2c04ccc25365'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
