"""empty message

Revision ID: 51b80ee2617f
Revises: 16786d0e2458
Create Date: 2014-04-10 12:50:30.592047

"""

# revision identifiers, used by Alembic.
revision = '51b80ee2617f'
down_revision = '16786d0e2458'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['post.id'], )
    )
    op.drop_table('unverified__user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unverified__user',
    sa.Column('id', sa.INTEGER(), server_default="nextval('unverified__user_id_seq'::regclass)", nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conf_key', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'unverified__user_pkey')
    )
    op.drop_table('categories')
    op.drop_table('category')
    ### end Alembic commands ###
