"""empty message

Revision ID: 561912558ff4
Revises: 2dbb2857331
Create Date: 2014-04-10 13:39:04.220732

"""

# revision identifiers, used by Alembic.
revision = '561912558ff4'
down_revision = '2dbb2857331'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
